services:
  webui:
    image: "ghcr.io/moonlightpacifist/sd-webui-forge-docker:latest"
    # build: .
    volumes:
      - "./data:/app/sd-webui"
    ports:
      - "7860:7860"
    environment:
      - "ARGS=--listen --enable-insecure-extension-access ${WEBUI_ARGS}" 
      - "UI=reforge"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
